id: P004322
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74384
  title: ཡོན་ཏན་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཟུག་རྔུའི་ཚ་གདུངས་སེལ་བའི་ཀཏྤཱུ་ར་དུས་མིན་འཆི་ཞགས་གཅོད་པའི་རལ་གྲི།
  author: ''
  volumes:
    3af0be72d6694faf814602c379010253:
      image_group_id: I4CZ74386
      title: ''
      volume_number: 1
      total_pages: 586
