id: P004322
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:10:32.924478
source_metadata:
  id: bdr:W4CZ74384
  title: ཡོན་ཏན་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཟུག་རྔུའི་ཚ་གདུངས་སེལ་བའི་ཀཏྤཱུ་ར་དུས་མིན་འཆི་ཞགས་གཅོད་པའི་རལ་གྲི།
  author: ''
  volumes:
    3af0be72d6694faf814602c379010253:
      image_group_id: I4CZ74386
      title: ''
      volume_number: 1
      total_pages: 586
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
