id: opecha:P004322
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74384
  title: ཡོན་ཏན་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཟུག་རྔུའི་ཚ་གདུངས་སེལ་བའི་ཀཏྤཱུ་ར་དུས་མིན་འཆི་ཞགས་གཅོད་པའི་རལ་གྲི།
  volume: ''
  author: ''
