id: IF16FB1F1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:53:02+00:00'
last_modified: '2022-06-07T21:58:59.687546+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74384
  title: ཡོན་ཏན་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཟུག་རྔུའི་ཚ་གདུངས་སེལ་བའི་ཀཏྤཱུ་ར་དུས་མིན་འཆི་ཞགས་གཅོད་པའི་རལ་གྲི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    16FE:
      image_group_id: I4CZ74386
      title: ''
      total_pages: 586
      order: 1
      base_file: 16FE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
